services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - ORIGIN=${ORIGIN}
      - DB_PATH=/app/data/svalbard.sqlite
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./data:/app/data
